bpdm:
    controller:
        search-request-limit: 100
    datasource:
        host: localhost
    description: '@project.description@'
    logging:
        unknown-user: Anonymous
    name: '@project.name@'
    saas:
        enabled: false
    security:
        enabled: false
    version: '@project.version@'
    poolClient:
      url: http://localhost
      port: 8080

management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ''
        url: jdbc:postgresql://${bpdm.datasource.host}:5432/bpdm
        username: bpdm
    flyway:
        enabled: true
        schemas: bpdmcdq
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: bpdmcdq
                jdbc:
                    batch_size: 16
                order_inserts: true
                order_updates: true
springdoc:
    api-docs:
        path: /docs/api-docs
    swagger-ui:
        csrf:
            enabled: true
        disable-swagger-default-url: true
        path: /ui/swagger-ui
        show-common-extensions: true
