bpdm:
    security:
        enabled: true
        cors-origins: '*'
        client-id: BPDM_Client
        realm: master
        auth-server-url: http://localhost:8180
        auth-url: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}/protocol/openid-connect/auth
        token-url: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}/protocol/openid-connect/token
        refresh-url: ${bpdm.security.token-url}

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}
                    jwk-set-uri: ${bpdm.security.auth-server-url}/realms/${bpdm.security.realm}/protocol/openid-connect/certs

springdoc:
    swagger-ui:
      oauth:
        clientId: PUBLIC_CLIENT
