bpdm:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    datasource:
        host: localhost
    pool-client:
        url: http://localhost:8080
    saas:
        host: ${BPDM_SAAS_HOST}
        api: data-exchange/rest/v4
        storage: ${BPDM_SAAS_STORAGE}
        datasource: ${BPDM_SAAS_DATASOURCE}
        api-key: ${BPDM_SAAS_KEY}
        import-limit: 100
        import-scheduler-cron-expr: "-"
        export-page-size: 100
        treat-invalid-bpn-as-new: false
        request-size-limit: 500
    gate-client:
        url: http://localhost:8080
    change-log:
        import-scheduler-cron-expr: "0 * * * * *"

spring:
    datasource:
        url: jdbc:postgresql://${bpdm.datasource.host}:5432/bpdm
        driverClassName: org.postgresql.Driver
        username: bpdm
        password:
    flyway:
        enabled: true
        schemas: bpdmcdq
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: bpdmcdq
    #Send updates and inserts out in batches to decrease network connections to the database
                jdbc:
                    batch_size: 16
                order_inserts: true
                order_updates: true
    main:
        allow-bean-definition-overriding: true
management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

springdoc:
    api-docs:
        enabled: true
        path: /docs/api-docs
    swagger-ui:
        csrf:
            enabled: true
        disable-swagger-default-url: true
        path: /ui/swagger-ui
        show-common-extensions: true

server:
    port: 8082