bpdm:
    client:
        oauth2-client-registration: bridge-client
        pool-security-enabled: true

spring:
    security:
        oauth2:
            client:
                provider:
                    catena-keycloak-provider:
                        issuer-uri: ${bpdm.security.auth-server-url:http://localhost:8180}/realms/${bpdm.security.realm:master}
                registration:
                    bridge-client:
                        authorization-grant-type: client_credentials
                        client-id: ${bpdm.security.client-id}
                        client-secret: ${bpdm.security.credentials.secret}
                        provider: catena-keycloak-provider
